version: "3.8"

services:
  # scraper:
  #   build:
  #     context: ./scraper
  #     dockerfile: Dockerfile-scraper
  #   container_name: scraper
  #   depends_on:
  #     - db

  scraperpy:
    build:
      context: ./scraperpy
      dockerfile: Dockerfile-scraperpy
    container_name: scraperpy
    depends_on:
      - db

  db:
    build:
      context: ./db
      dockerfile: Dockerfile-postgres
    container_name: db
    ports:
      - "5432:5432"

  server:
    build:
      context: ./backend
      dockerfile: Dockerfile-backend
    container_name: server
    ports:
      - "3000:3000"
    depends_on:
      - db

  client:
    build:
      context: ./client
      dockerfile: Dockerfile-client
    container_name: client
    ports:
      - "8080:8080"
    depends_on:
      - server
