# Use an official Python runtime as a parent image
FROM python:3.10-slim
WORKDIR /usr/src/app
COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
RUN playwright install
RUN playwright install-deps
COPY . . 
# Add a shell script to run init-db.py first, then start the spider
COPY ./docker-entrypoint.sh /
RUN chmod +x /docker-entrypoint.sh
ENTRYPOINT ["/docker-entrypoint.sh"]
